esudo: false
branches:
  only:
  - master
  - develop
language: node_js
node_js:
- '6'
before_install:
- 'pwd && ls -als'
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.25.4
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
- 'npm install'
script:
- 'npm run lint'
- 'npm run build'
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
