esudo: false
branches:
  only:
  - master
  - develop
language: node_js
node_js:
- '6'
before_install:
- 'pwd && ls -als'
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
- 'yarn install'
- 'ls -als node_modules/@types'
- 'yarn pouchdb:install'
script:
- 'yarn run lint'
- 'yarn run build'
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
