esudo: false
branches:
  only:
  - master
  - develop
language: node_js
node_js:
- '8'
before_install:
- 'pwd && ls -als'
- npm -g install npm@6.*.*
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
- 'npm ci'
# - 'npm run __postinstall'
script:
- 'npm run lint'
- 'npm run build'
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
